CREATE DATABASE apartments;

CREATE DATABASE apartments
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
-- all good
create table main_apartments(
    apt_id serial primary key,
    building_name TEXT not null,
    apt_number text not null,
    total_rooms integer
);
-- all good
create table rooms(
    room_id serial primary key,
    apt_id serial references main_apartments(apt_id),
    room_number text not null,
    room_type text,
    capacity integer,
    vacant boolean not null
);

-- all good
create table tenants(
    tenant_id text primary key,
    room_id serial references rooms(room_id),
    apt_id serial references main_apartments(apt_id),
    name text not null,
    emirates_id text not null,
    phone_number integer not null,
    email text,
    date_settle_in date not null
);

-- all good
create table rent_payments(
    payment_id text primary key,
    tenant_id text references tenants(tenant_id),
    month_year text not null,
    amount_paid integer not null,
    amount_due integer,
    notes text
);

-- all good
create table apartment_expenses(
    expense_id serial primary key,
    apt_id serial references main_apartments(apt_id),
    month_year text not null,
    amount_paid integer not null,
    notes text
);
-- all good
create table monthly_reports(
    report_id text primary key,
    apt_id serial references main_apartments(apt_id),
    month_year text not null,
    total_rent_due integer not null,
    total_rent_paid integer not null,
    total_expenses integer not null
);

-- this table is only filled when the tenant is discharged or changed apartment.
create table tenant_history(
    record_id text primary key, -- uuid is generated by the server
    apt_id serial references main_apartments(apt_id),
    tenant_id text references tenants(tenant_id),
    date_settle_in date not null,
    date_settle_out date not null,
    amount_paid integer not null,
    amount_due integer not null,
    notes text
);

-- all good
create table contracts(
    contract_id text primary key, -- uuid is generated by the server
    tenant_id text references tenants(tenant_id),
    contract_start date not null,
    contract_end date not null,
    rent integer not null,
    active boolean not null,
    notes text
);


ALTER TABLE tenants ALTER COLUMN date_settle_in SET NOT NULL;
ALTER TABLE tenants ALTER COLUMN date_settle_in TYPE DATE; -- gives error
ALTER TABLE tenants ALTER COLUMN date_settle_in TYPE DATE USING date_settle_in::date;
ALTER TABLE tenants DROP COLUMN  assigned_monthly_rent;

ALTER TABLE contracts ADD COLUMN current_contract BOOLEAN;
ALTER TABLE contracts ALTER COLUMN current_contract SET NOT NULL;

ALTER TABLE contracts
    RENAME COLUMN current_contract TO active;

ALTER TABLE tenants
    ADD COLUMN apt_id INTEGER references main_apartments(apt_id);

ALTER TABLE rooms
    ADD COLUMN vacant BOOLEAN;
ALTER TABLE rooms
    DROP COLUMN vacant;

delete from tenants where tenant_id = $1;
delete from contracts where tenant_id = $2;
update rooms set vacant = true where room_id = $3;